version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    command: gunicorn kanban.wsgi:application --bind 0.0.0.0:8000 --workers 2
