version: "3.9"

services:
  web:
    #build:
    #  context: .            # Path to your project (where Dockerfile is located)
    #  dockerfile: Dockerfile
    image: kanban-board-web:latest
    container_name: kanban_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/app              # Mount current directory into /app
    depends_on:
      - db
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass

  db:
    image: postgres:15
    container_name: kanban_db
    restart: always
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kanban_pgadmin
    restart: always
    ports:
      - "8090:80"    # Access pgAdmin in browser
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db


volumes:
  postgres_data:

