apiVersion: v1
kind: Service
metadata:
  name: kanban-web-svc
  namespace: kanban
  labels:
    app: kanban-board-web
spec:
  type: NodePort
  selector:
    app: kanban-board-web
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30001
