apiVersion: v1
kind: Pod
metadata:
  name: kanban-db
  labels:
    app: kanban-db
spec:
  containers:
    - name: kanban-db
      image: postgres:15
      env:
        - name: POSTGRES_DB
          value: "kanban_db"
        - name: POSTGRES_USER
          value: "kanban_user"
        - name: POSTGRES_PASSWORD
          value: "kanban_pass"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      emptyDir: {}
