apiVersion: v1
kind: Service
metadata:
  name: kanban-db-svc
  namespace: kanban
  labels:
    app: kanban-db
spec:
  type: ClusterIP
  selector:
    app: kanban-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
