# Generated by Django 5.2.5 on 2025-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('in-review', 'In Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
            ],
        ),
    ]
