# Generated by Django 5.2.5 on 2025-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.CharField(choices=[('office', 'Office'), ('home', 'Home')], default='office', max_length=20),
        ),
    ]
