# Generated by Django 5.2.5 on 2025-09-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.CharField(default='office', max_length=50),
        ),
    ]
