# Generated by Django 5.2.5 on 2025-09-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_task_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.space'),
        ),
    ]
