# Generated by Django 5.2.5 on 2025-09-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_migrate_workspace_to_fk'),
    ]

    operations = [
        # Remove the old string-based 'workspace' field
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
        # Rename the temporary FK 'workspace_fk' to 'workspace'
        migrations.RenameField(
            model_name='task',
            old_name='workspace_fk',
            new_name='workspace',
        ),
    ]
