# Generated by Django 5.2.5 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_task_workspace_fk_alter_task_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
