# Generated by Django 5.2.5 on 2025-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
